### ISSUE TITLE
Cannot run the test in bitbucket pipelines

### ISSUE THREAD

**Issue by diondirza** [getgauge/taiko#1192]
I run it in bitbucket pipelines yet it yields an error, probably it could be some lib is missing here. I couldn't figure it out.

### Expected behavior
It should be running without an issue like in the local

### Actual behavior
![image](https://user-images.githubusercontent.com/10954870/79108100-31b2ca80-7da8-11ea-9f39-66b6c2dd4279.png)

### Steps to reproduce
1. add taiko as dev dependencies 
2. add test script in the pipeline configuration 
3. run the test in the bitbucket pipeline

```
# bitbucket-pipeline.yml
image: node:12.16.1

definitions:
  caches:
    nodecustom: ./node_modules
    yarn: /usr/local/share/.cache/yarn
  steps:
    - step: &test-e2e
        name: Run testing E2E
        caches:
          - nodecustom
          - yarn
        script:
          - yarn setup
          - yarn test:e2e
    
pipelines:
  pull-requests:
    '**': #this runs as default for any branch not elsewhere defined
      - step: *test-e2e
```

### Versions
```
node: 12.16.1
taiko:  1.0.7
```
